name: imei_validator
version: 0.2.1
description: A library for checking cell phone IMEIs with the Luhn algorithm.
homepage: https://github.com/thinkdigitalrepair/imei_validator
dev_dependencies:
  test: ^1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'